// Generated by scripts/generate-openapi-client.mjs from docs/api/openapi.yaml.
// Do not edit by hand. Run pnpm -C frontend generate:api.

export const apiPaths = {
  health: '/api/v1/health',
  ready: '/api/v1/ready',
  authMe: '/api/v1/auth/me',
  authLocalLogin: '/api/v1/auth/local-login',
  authLogout: '/api/v1/auth/logout',
  users: '/api/v1/users',
  user: (userId: string) => `/api/v1/users/${userId}`,
  projects: '/api/v1/projects',
  project: (projectId: string) => `/api/v1/projects/${projectId}`,
  projectMemberships: (projectId: string) => `/api/v1/projects/${projectId}/memberships`,
  projectMembership: (projectId: string, membershipId: string) =>
    `/api/v1/projects/${projectId}/memberships/${membershipId}`,
  suites: '/api/v1/suites',
  suite: (suiteId: string, projectId: string) => `/api/v1/suites/${suiteId}?projectId=${projectId}`,
  projectSuiteAssignments: (projectId: string) => `/api/v1/projects/${projectId}/suite-assignments`,
  projectSuiteAssignment: (projectId: string, assignmentId: string) =>
    `/api/v1/projects/${projectId}/suite-assignments/${assignmentId}`,
  projectCycles: (projectId: string) => `/api/v1/projects/${projectId}/cycles`,
  projectCycle: (projectId: string, cycleId: string) =>
    `/api/v1/projects/${projectId}/cycles/${cycleId}`,
  generationJobs: '/api/v1/generation-jobs',
  requirements: (projectId: string) => `/api/v1/requirements?projectId=${projectId}`,
  requirement: (projectId: string, requirementId: string) =>
    `/api/v1/requirements/${requirementId}?projectId=${projectId}`,
  approveRequirement: (projectId: string, requirementId: string) =>
    `/api/v1/requirements/${requirementId}:approve?projectId=${projectId}`,
  testCases: (projectId: string) => `/api/v1/test-cases?projectId=${projectId}`,
  filteredTestCases: (
    projectId: string,
    projectSuiteAssignmentId?: string | null,
    testCycleId?: string | null,
    requirementId?: string | null
  ) => {
    const params = new URLSearchParams({ projectId });
    if (projectSuiteAssignmentId) params.set('projectSuiteAssignmentId', projectSuiteAssignmentId);
    if (testCycleId) params.set('testCycleId', testCycleId);
    if (requirementId) params.set('requirementId', requirementId);
    return `/api/v1/test-cases?${params.toString()}`;
  },
  createTestCase: '/api/v1/test-cases',
  adhocTestCases: (projectId: string, projectSuiteAssignmentId: string, testCycleId: string) => {
    const params = new URLSearchParams({ projectId, projectSuiteAssignmentId, testCycleId });
    return `/api/v1/test-cases/adhoc?${params.toString()}`;
  },
  createAdhocTestCase: '/api/v1/test-cases/adhoc',
  generateTestCases: '/api/v1/test-cases:generate',
  importTestCasesCsv: (
    projectId: string,
    projectSuiteAssignmentId: string | null | undefined,
    testCycleId: string | null | undefined,
    requirementId: string
  ) => {
    const params = new URLSearchParams({ projectId, requirementId });
    if (projectSuiteAssignmentId) params.set('projectSuiteAssignmentId', projectSuiteAssignmentId);
    if (testCycleId) params.set('testCycleId', testCycleId);
    return `/api/v1/test-cases:import-csv?${params.toString()}`;
  },
  testCaseCsvSample: '/api/v1/test-cases:csv-sample',
  importAdhocTestCasesCsv: (
    projectId: string,
    projectSuiteAssignmentId: string,
    testCycleId: string
  ) => {
    const params = new URLSearchParams({ projectId, projectSuiteAssignmentId, testCycleId });
    return `/api/v1/test-cases/adhoc:import-csv?${params.toString()}`;
  },
  adhocTestCaseCsvSample: '/api/v1/test-cases/adhoc:csv-sample',
  testCase: (projectId: string, testCaseId: string) =>
    `/api/v1/test-cases/${testCaseId}?projectId=${projectId}`
} as const;

export type Capability =
  | 'USER_ACCESS_MANAGE'
  | 'PROJECT_CREATE'
  | 'PROJECT_VIEW'
  | 'PROJECT_MANAGE_USERS'
  | 'PROJECT_MANAGE_SUITES'
  | 'PROJECT_MANAGE_CYCLES'
  | 'SUITE_CREATE'
  | 'SUITE_EDIT'
  | 'SUITE_DELETE'
  | 'SUITE_MANAGE_ASSIGNMENTS'
  | 'CYCLE_CREATE'
  | 'CYCLE_EDIT'
  | 'CYCLE_DELETE'
  | 'REQUIREMENT_CREATE'
  | 'REQUIREMENT_EDIT'
  | 'REQUIREMENT_APPROVE'
  | 'REQUIREMENT_DELETE_UNLINKED'
  | 'TEST_CASE_CREATE'
  | 'TEST_CASE_EDIT'
  | 'TEST_CASE_ASSIGN'
  | 'TEST_CASE_DELETE_DRAFT'
  | 'PREDEFINED_CASE_GENERATE'
  | 'PREDEFINED_CASE_DELETE'
  | 'TEST_CASE_VIEW_EXPORT'
  | 'REPORT_VIEW'
  | 'UPLOAD_ACCESS'
  | 'GENERATION_JOB_ACCESS'
  | 'EXPORT_DOWNLOAD'
  | 'AUDIT_VIEW'
  | 'EVIDENCE_ACCESS';

export interface ProblemDetails {
  type?: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  violations?: string[];
  rowErrors?: string[];
  [key: string]: unknown;
}

export interface SystemStatusResponse {
  status: 'UP' | 'DOWN';
  check: 'health' | 'ready';
  service: string;
  timestamp: string;
}

export interface AuthSessionResponse {
  userId: string;
  tenantId: string;
  objectId: string;
  firstName: string;
  lastName: string;
  contactEmail: string;
  globalAdministrator: boolean;
  principalKey: string;
  globalCapabilities: Capability[];
  projectPermissions: Record<string, AccessPermission[]>;
}

export interface LocalLoginRequest {
  username: string;
  password: string;
}

export type UserRole = 'ADMINISTRATOR' | 'TEST_MANAGER' | 'TEST_LEAD' | 'TEST_ANALYST';
export type UserStatus = 'ACTIVE' | 'INACTIVE';
export type PersistedUserStatus = 'ACTIVE' | 'DISABLED';
export type AccessPermission =
  | 'VIEW'
  | 'CREATE'
  | 'EDIT'
  | 'EXECUTE'
  | 'DELETE'
  | 'APPROVE_REQUIREMENTS'
  | 'MANAGE_ASSIGNMENTS';

export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  confirmPassword: string;
  role: UserRole;
  status: UserStatus;
  projectIds: string[];
  suiteAssignmentIds: string[];
  testCycleIds: string[];
  permissions: AccessPermission[];
}

export interface UpdateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  status: UserStatus;
  projectIds: string[];
  permissions: AccessPermission[];
  newPassword?: string;
  confirmNewPassword?: string;
}

export interface UserSummary {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  status: PersistedUserStatus;
  projectIds: string[];
  permissions: AccessPermission[];
}

export interface UserListResponse {
  users: UserSummary[];
}

export interface ProjectSummary {
  id: string;
  projectKey: string;
  name: string;
  description: string | null;
  active: boolean;
  suiteCount: number;
  cycleCount: number;
  userCount: number;
}

export interface ProjectListResponse {
  scopeLabel: 'All Projects' | 'My Projects';
  allProjects: boolean;
  canCreateProject: boolean;
  globalCapabilities: Capability[];
  projects: ProjectSummary[];
}

export interface ProjectDetailResponse {
  project: ProjectSummary;
  capabilities: Capability[];
  permissions: AccessPermission[];
  memberships: ProjectMembershipSummary[];
}

export interface CreateProjectRequest {
  projectKey?: string;
  name: string;
  description?: string;
}

export type ProjectRole = 'TEST_MANAGER' | 'TEST_LEAD' | 'TEST_ANALYST';
export type ProjectRoleLabel = 'Test Manager' | 'Test Lead' | 'Test Analyst';
export type MembershipStatus = 'ACTIVE' | 'DISABLED';
export type InvitationStatus = 'INVITED' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';

export interface ProjectMembershipSummary {
  id: string;
  userId: string;
  firstName: string;
  lastName: string;
  email: string;
  projectRole: ProjectRoleLabel;
  membershipStatus: MembershipStatus;
  invitationStatus: InvitationStatus;
  entraBound: boolean;
}

export interface ProjectMembershipListResponse {
  memberships: ProjectMembershipSummary[];
}

export interface AddProjectMemberRequest {
  firstName: string;
  lastName: string;
  email: string;
  projectRole: ProjectRole;
}

export interface ChangeProjectMemberRoleRequest {
  projectRole: ProjectRole;
  allowLastManagerOverride?: boolean;
}

export interface SuiteCatalogSummary {
  id: string;
  suiteKey: string;
  name: string;
  description: string | null;
  active: boolean;
  version: number;
}

export interface SuiteCatalogResponse {
  suites: SuiteCatalogSummary[];
}

export interface ProjectSuiteAssignmentSummary {
  id: string;
  projectId: string;
  suiteId: string;
  suiteKey: string;
  name: string;
  description: string | null;
  active: boolean;
  version: number;
  suiteVersion: number;
}

export interface ProjectSuiteAssignmentListResponse {
  assignments: ProjectSuiteAssignmentSummary[];
}

export interface AssignSuiteRequest {
  suiteId?: string;
  name: string;
  description?: string;
}

export interface UpdateSuiteRequest {
  name: string;
  description?: string;
}

export interface ProjectCycleSummary {
  id: string;
  projectId: string;
  name: string;
  startDate: string | null;
  endDate: string | null;
  description: string | null;
  active: boolean;
  version: number;
}

export interface ProjectCycleListResponse {
  cycles: ProjectCycleSummary[];
}

export interface SaveCycleRequest {
  name: string;
  startDate?: string;
  endDate?: string;
  description?: string;
}

export interface CreateManualRequirementRequest {
  projectId: string;
  projectSuiteAssignmentId: string;
  testCycleId: string;
  header: string;
  description: string;
}

export interface UpdateRequirementRequest {
  header: string;
  description: string;
  acceptanceCriteria?: string;
  assumptions?: string;
  dependencies?: string;
}

export type RequirementStatus = 'Draft' | 'Approved';
export type RequirementSourceType = 'MANUAL' | 'PDF' | 'DOCX' | 'DOC' | 'CSV' | 'AI';

export interface RequirementSummary {
  id: string;
  projectId: string;
  projectSuiteAssignmentId: string;
  suiteId: string;
  suiteName: string;
  testCycleId: string;
  cycleName: string;
  reqId: string;
  header: string;
  description: string;
  acceptanceCriteria: string;
  assumptions: string;
  dependencies: string;
  status: RequirementStatus;
  sourceType: RequirementSourceType;
  createdDate: string;
  approvedAt: string | null;
  approvedBy: string | null;
  version: number;
}

export interface RequirementListResponse {
  requirements: RequirementSummary[];
}

export interface RequirementSelectionContext {
  projectId: string;
  projectSuiteAssignmentId?: string | null;
  testCycleId?: string | null;
  requirementId: string;
}

export interface CreateManualTestCaseRequest extends RequirementSelectionContext {
  header: string;
  description: string;
}

export interface AdhocSelectionContext {
  projectId: string;
  projectSuiteAssignmentId: string;
  testCycleId: string;
}

export interface CreateAdhocTestCaseRequest extends AdhocSelectionContext {
  header: string;
  description: string;
}

export type TestCaseStatus =
  | 'Draft'
  | 'Inprogress'
  | 'Defect'
  | 'Resolved'
  | 'Not applicable'
  | 'Retest';
export type TestCaseSourceType =
  | 'MANUAL'
  | 'CSV'
  | 'AI'
  | 'PREDEFINED'
  | 'MANUAL_ADHOC'
  | 'CSV_ADHOC';

export interface UpdateTestCaseRequest {
  assigneeMembershipId?: string | null;
  dueDate?: string | null;
  header: string;
  description: string;
  status: TestCaseStatus;
}

export interface TestCaseSummary {
  id: string;
  projectId: string;
  projectName: string;
  projectSuiteAssignmentId: string;
  suiteId: string;
  suiteName: string;
  testCycleId: string;
  cycleName: string;
  requirementId: string | null;
  reqId: string | null;
  requirementHeader: string | null;
  requirementDescription: string | null;
  testCaseId: string;
  header: string;
  description: string;
  status: TestCaseStatus;
  sourceType: TestCaseSourceType;
  createdDate: string;
  dueDate: string | null;
  assigneeMembershipId: string | null;
  assigneeName: string | null;
  version: number;
}

export interface TestCaseListResponse {
  testCases: TestCaseSummary[];
}

export interface TestCaseGenerationResult {
  jobId: string;
  importedCount: number;
  testCases: TestCaseSummary[];
}
